name: app_web_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^8.1.1+1
  google_sign_in: ^5.0.7
  url_launcher: ^6.0.2
  flutter_facebook_auth: ^3.5.1
  just_audio: ^0.9.7
  assets_audio_player: ^3.0.3+6
  flutter_bloc: ^7.1.0
  random_string: ^2.3.1
  get_it: ^7.2.0
  flutter_screenutil: ^5.0.0+2
  equatable: ^2.0.3
  page_transition: ^2.0.2
  connectivity_plus: ^1.0.4
  shared_preferences: ^2.0.6
  app_settings: ^4.1.1
  permission_handler: ^8.1.4+2
  image_picker_for_web: ^2.1.3
  image_picker: ^0.7.2+1
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0-nullsafety
  photo_view: ^0.12.0
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  file_picker: ^4.0.0
  pretty_dio_logger: ^1.1.1
  flutter_svg: ^0.22.0
  flash: ^2.0.1
  logger: ^1.0.0
  agora_rtc_engine: ^4.0.6
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator: any
  flutter_launcher_icons: ^0.9.1
  flutter_app_name: ^0.1.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo/logomain.png"
  remove_alpha_ios: true

flutter_app_name:
  name: "Couple"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/infor/
    - assets/images/splash/
    - assets/logo/
    - assets/images/
    - assets/icons/

