name: app_web_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^8.1.1+1
  google_sign_in: ^5.0.7
  flutter_app_badger: ^1.2.0
  url_launcher: ^6.0.2
#  #web
#  cloud_firestore_web: ^2.4.0
#  firebase_storage_web: ^3.0.1
#  firebase_auth_web: ^3.0.1
#  firebase_core_web: ^1.1.0
#  firebase_messaging_web: ^2.0.4
  just_audio: ^0.9.7
  assets_audio_player: ^3.0.3+6
  flutter_bloc: ^7.1.0
  random_string: ^2.3.1
  get_it: ^7.2.0
  rxdart: ^0.27.1
  flutter_screenutil: ^5.0.0+2
  equatable: ^2.0.3
  page_transition: ^2.0.2
  connectivity_plus: ^1.0.4

  shared_preferences: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  app_settings: ^4.1.1
  permission_handler: ^8.1.4+2
  image_picker_for_web: ^2.1.3
  image_picker: ^0.7.2+1
  image_cropper: ^1.4.0
  cached_network_image: ^3.0.0-nullsafety
  photo_view: ^0.11.1
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  file_picker: ^4.0.0
  #audioplayers: ^0.19.1
  pretty_dio_logger: ^1.1.1
  flutter_svg: ^0.22.0
  flash: ^2.0.1
  logger: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  built_value_generator: any
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/infor/
    - assets/images/splash/
    - assets/logo/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
